require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/initializers/simple_form_bootstrap.rb"

Layout/LineLength:
  Max: 90
  IgnoredPatterns:
    - '\A(\s)*#'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"