dist: xenial
cache:
  bundler: true
  yarn: true
language: ruby
env:
  global:
    - RAILS_ENV=test
install:
  - travis_retry nvm install 13.5.0
  - bundle
  - yarn
before_script:
  - bundle exec rails webpacker:compile
script:
  - bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
