dist: xenial
cache: bundler
language: ruby
script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rake
  - bundle exec rubocop --require rubocop-rails
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
